const DATA = {
  roles: ['TOP', 'JUG', 'MID', 'BOT', 'SUP'],
  conditions: [
    { id: 'perfect', label: '최상', starsMod: 1, color: 'text-blue-400' },
    { id: 'good', label: '좋음', starsMod: 0, color: 'text-green-400' },
    { id: 'normal', label: '보통', starsMod: 0, color: 'text-gray-400' },
    { id: 'bad', label: '나쁨', starsMod: -1, color: 'text-orange-400' },
    { id: 'injured', label: '부상', starsMod: -2, color: 'text-red-600' }
  ],
  teams: [
    { id: 'HLE', name: 'Hanwha Life Esports', color: '#f37321', logo: 'logo/hle.svg' },
    { id: 'T1', name: 'T1', color: '#e2012d', logo: 'logo/t1.svg' },
    { id: 'GEN', name: 'GEN.G', color: '#cfb887', logo: 'logo/gen.svg' },
    { id: 'KT', name: 'KT Rolster', color: '#ff0a07', logo: 'logo/kt.svg' },
    { id: 'DK', name: 'Dplus KIA', color: '#000000', logo: 'logo/dk.svg' },
    { id: 'BRO', name: 'HANJIN BRION', color: '#00492b', logo: 'logo/bro.svg' },
    { id: 'BFX', name: 'BNK FearX', color: '#fbe400', logo: 'logo/bfx.svg' },
    { id: 'KRX', name: 'KIWOOM DRX', color: '#001c58', logo: 'logo/krx.svg' },
    { id: 'NS', name: 'Nongshim RedForce', color: '#de2027', logo: 'logo/ns.svg' },
    { id: 'DNS', name: 'DN SOOPers', color: '#0c50f1', logo: 'logo/dns.svg' }
  ],
  players: [
    { id: 'p1', name: 'PerfecT', teamId: 'KT', role: 'TOP', tier: 5, img: 'players/perfect.webp' },
    { id: 'p2', name: 'Cuzz', teamId: 'KT', role: 'JUG', tier: 4, img: 'players/cuzz.webp' },
    { id: 'p3', name: 'Bdd', teamId: 'KT', role: 'MID', tier: 5, img: 'players/bdd.webp' },
    { id: 'p4', name: 'Aiming', teamId: 'KT', role: 'BOT', tier: 5, img: 'players/aiming.webp' },
    { id: 'p5', name: 'Effort', teamId: 'KT', role: 'SUP', tier: 4, img: 'players/effort.webp' },
    { id: 'p6', name: 'FenRir', teamId: 'KT', role: 'BOT', tier: 3, img: 'players/fenrir.webp' },
    { id: 'p7', name: 'Ghost', teamId: 'KT', role: 'SUP', tier: 3, img: 'players/ghost.webp' },
    { id: 'p8', name: 'Pollu', teamId: 'KT', role: 'SUP', tier: 3, img: 'players/pollu.webp' },
    { id: 'p9', name: 'Kiin', teamId: 'GEN', role: 'TOP', tier: 5, img: 'players/kiin.webp' },
    { id: 'p10', name: 'Canyon', teamId: 'GEN', role: 'JUG', tier: 5, img: 'players/canyon.webp' },
    { id: 'p11', name: 'Chovy', teamId: 'GEN', role: 'MID', tier: 5, img: 'players/chovy.webp' },
    { id: 'p12', name: 'Ruler', teamId: 'GEN', role: 'BOT', tier: 5, img: 'players/ruler.webp' },
    { id: 'p13', name: 'Duro', teamId: 'GEN', role: 'SUP', tier: 4, img: 'players/duro.webp' },
    { id: 'p14', name: 'Zeus', teamId: 'HLE', role: 'TOP', tier: 5, img: 'players/zeus.webp' },
    { id: 'p15', name: 'Kanavi', teamId: 'HLE', role: 'JUG', tier: 5, img: 'players/kanavi.webp' },
    { id: 'p16', name: 'Zeka', teamId: 'HLE', role: 'MID', tier: 5, img: 'players/zeka.webp' },
    { id: 'p17', name: 'Gumayusi', teamId: 'HLE', role: 'BOT', tier: 5, img: 'players/gumayusi.webp' },
    { id: 'p18', name: 'Delight', teamId: 'HLE', role: 'SUP', tier: 4, img: 'players/delight.webp' },
    { id: 'p19', name: 'Bluffing', teamId: 'HLE', role: 'SUP', tier: 3, img: 'players/bluffing.webp' },
    { id: 'p20', name: 'Doran', teamId: 'T1', role: 'TOP', tier: 5, img: 'players/doran.webp' },
    { id: 'p21', name: 'Oner', teamId: 'T1', role: 'JUG', tier: 5, img: 'players/oner.webp' },
    { id: 'p22', name: 'Faker', teamId: 'T1', role: 'MID', tier: 5, img: 'players/faker.webp' },
    { id: 'p23', name: 'Peyz', teamId: 'T1', role: 'BOT', tier: 4, img: 'players/peyz.webp' },
    { id: 'p24', name: 'Keria', teamId: 'T1', role: 'SUP', tier: 5, img: 'players/keria.webp' },
    { id: 'p25', name: 'Siwoo', teamId: 'DK', role: 'TOP', tier: 5, img: 'players/siwoo.webp' },
    { id: 'p26', name: 'Lucid', teamId: 'DK', role: 'JUG', tier: 5, img: 'players/lucid.webp' },
    { id: 'p27', name: 'ShowMaker', teamId: 'DK', role: 'MID', tier: 5, img: 'players/showmaker.webp' },
    { id: 'p28', name: 'Smash', teamId: 'DK', role: 'BOT', tier: 4, img: 'players/smash.webp' },
    { id: 'p29', name: 'Career', teamId: 'DK', role: 'SUP', tier: 4, img: 'players/career.webp' },
    { id: 'p30', name: 'Sharvel', teamId: 'DK', role: 'JUG', tier: 3, img: 'players/sharvel.webp' },
    { id: 'p31', name: 'Casting', teamId: 'BRO', role: 'TOP', tier: 4, img: 'players/casting.webp' },
    { id: 'p32', name: 'GIDEON', teamId: 'BRO', role: 'JUG', tier: 3, img: 'players/gideon.webp' },
    { id: 'p33', name: 'Roamer', teamId: 'BRO', role: 'MID', tier: 4, img: 'players/roamer.webp' },
    { id: 'p34', name: 'Teddy', teamId: 'BRO', role: 'BOT', tier: 4, img: 'players/teddy.webp' },
    { id: 'p35', name: 'Namgung', teamId: 'BRO', role: 'SUP', tier: 3, img: 'players/namgung.webp' },
    { id: 'p36', name: 'Loki', teamId: 'BRO', role: 'MID', tier: 3, img: 'players/loki.webp' },
    { id: 'p37', name: 'Clear', teamId: 'BFX', role: 'TOP', tier: 4, img: 'players/clear.webp' },
    { id: 'p38', name: 'Raptor', teamId: 'BFX', role: 'JUG', tier: 4, img: 'players/raptor.webp' },
    { id: 'p39', name: 'VicLa', teamId: 'BFX', role: 'MID', tier: 4, img: 'players/vicla.webp' },
    { id: 'p40', name: 'Daystar', teamId: 'BFX', role: 'MID', tier: 3, img: 'players/daystar.webp' },
    { id: 'p41', name: 'Taeyoon', teamId: 'BFX', role: 'BOT', tier: 4, img: 'players/taeyoon.webp' },
    { id: 'p42', name: 'Kellin', teamId: 'BFX', role: 'SUP', tier: 4, img: 'players/kellin.webp' },
    { id: 'p43', name: 'Slayer', teamId: 'BFX', role: 'BOT', tier: 3, img: 'players/slayer.webp' },
    { id: 'p44', name: 'Rich', teamId: 'KRX', role: 'TOP', tier: 4, img: 'players/rich.webp' },
    { id: 'p45', name: 'Willer', teamId: 'KRX', role: 'JUG', tier: 3, img: 'players/willer.webp' },
    { id: 'p46', name: 'Ucal', teamId: 'KRX', role: 'MID', tier: 4, img: 'players/ucal.webp' },
    { id: 'p47', name: 'Jiwoo', teamId: 'KRX', role: 'BOT', tier: 3, img: 'players/jiwoo.webp' },
    { id: 'p48', name: 'Andil', teamId: 'KRX', role: 'SUP', tier: 3, img: 'players/andil.webp' },
    { id: 'p49', name: 'Vincenzo', teamId: 'KRX', role: 'JUG', tier: 3, img: 'players/vincenzo.webp' },
    { id: 'p50', name: 'LazyFeel', teamId: 'KRX', role: 'BOT', tier: 3, img: 'players/lazyfeel.webp' },
    { id: 'p51', name: 'Kingen', teamId: 'NS', role: 'TOP', tier: 5, img: 'players/kingen.webp' },
    { id: 'p52', name: 'Sponge', teamId: 'NS', role: 'JUG', tier: 3, img: 'players/sponge.webp' },
    { id: 'p53', name: 'Scout', teamId: 'NS', role: 'MID', tier: 5, img: 'players/scout.webp' },
    { id: 'p54', name: 'Diable', teamId: 'NS', role: 'BOT', tier: 4, img: 'players/diable.webp' },
    { id: 'p55', name: 'Lehends', teamId: 'NS', role: 'SUP', tier: 5, img: 'players/lehends.webp' },
    { id: 'p56', name: 'Calix', teamId: 'NS', role: 'MID', tier: 3, img: 'players/calix.webp' },
    { id: 'p57', name: 'Pleata', teamId: 'NS', role: 'SUP', tier: 3, img: 'players/pleata.webp' },
    { id: 'p58', name: 'DuDu', teamId: 'DNS', role: 'TOP', tier: 5, img: 'players/dudu.webp' },
    { id: 'p59', name: 'Pyosik', teamId: 'DNS', role: 'JUG', tier: 3, img: 'players/pyosik.webp' },
    { id: 'p60', name: 'Clozer', teamId: 'DNS', role: 'MID', tier: 3, img: 'players/clozer.webp' },
    { id: 'p61', name: 'deokdam', teamId: 'DNS', role: 'BOT', tier: 3, img: 'players/deokdam.webp' },
    { id: 'p62', name: 'Peter', teamId: 'DNS', role: 'SUP', tier: 3, img: 'players/peter.webp' },
    { id: 'p63', name: 'Life', teamId: 'DNS', role: 'SUP', tier: 3, img: 'players/life.webp' },
    { id: 'p64', name: 'DDoiv', teamId: 'DNS', role: 'JUG', tier: 3, img: 'players/ddoiv.webp' },
    { id: 'p65', name: 'Enosh', teamId: 'DNS', role: 'BOT', tier: 3, img: 'players/enosh.webp' },
    { id: 'p66', name: 'Quantum', teamId: 'DNS', role: 'SUP', tier: 3, img: 'players/quantum.webp' }
  ],
  champions: [
    // TOP
    { id: 'Aatrox', name: '아트록스', role: 'TOP', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Aatrox.png' },
    { id: 'Camille', name: '카밀', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Camille.png' },
    { id: 'Chogath', name: '초가스', role: 'TOP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Chogath.png' },
    { id: 'Darius', name: '다리우스', role: 'TOP', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Darius.png' },
    { id: 'DrMundo', name: '문도 박사', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/DrMundo.png' },
    { id: 'Fiora', name: '피오라', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Fiora.png' },
    { id: 'Gangplank', name: '갱플랭크', role: 'TOP', tier: 4, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Gangplank.png' },
    { id: 'Garen', name: '가렌', role: 'TOP', tier: 5, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Garen.png' },
    { id: 'Gnar', name: '나르', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Gnar.png' },
    { id: 'Gragas', name: '그라가스', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Gragas.png' },
    { id: 'Gwen', name: '그웬', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Gwen.png' },
    { id: 'Illaoi', name: '일라오이', role: 'TOP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Illaoi.png' },
    { id: 'Irelia', name: '이렐리아', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Irelia.png' },
    { id: 'Jax', name: '잭스', role: 'TOP', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Jax.png' },
    { id: 'Jayce', name: '제이스', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Jayce.png' },
    { id: 'KSante', name: '크산테', role: 'TOP', tier: 'OP', img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/KSante.png' },
    { id: 'Kayle', name: '케일', role: 'TOP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kayle.png' },
    { id: 'Kennen', name: '케넨', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kennen.png' },
    { id: 'Kled', name: '클레드', role: 'TOP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kled.png' },
    { id: 'Malphite', name: '말파이트', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Malphite.png' },
    { id: 'Mordekaiser', name: '모데카이저', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Mordekaiser.png' },
    { id: 'Nasus', name: '나서스', role: 'TOP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Nasus.png' },
    { id: 'Olaf', name: '올라프', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Olaf.png' },
    { id: 'Ornn', name: '오른', role: 'TOP', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ornn.png' },
    { id: 'Pantheon', name: '판테온', role: 'TOP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Pantheon.png' },
    { id: 'Poppy', name: '뽀삐', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Poppy.png' },
    { id: 'Quinn', name: '퀸', role: 'TOP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Quinn.png' },
    { id: 'Renekton', name: '레넥톤', role: 'TOP', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Renekton.png' },
    { id: 'Riven', name: '리븐', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Riven.png' },
    { id: 'Rumble', name: '럼블', role: 'TOP', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Rumble.png' },
    { id: 'Sett', name: '세트', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Sett.png' },
    { id: 'Shen', name: '쉔', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Shen.png' },
    { id: 'Singed', name: '신지드', role: 'TOP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Singed.png' },
    { id: 'Sion', name: '사이온', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Sion.png' },
    { id: 'Teemo', name: '티모', role: 'TOP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Teemo.png' },
    { id: 'Tryndamere', name: '트린다미어', role: 'TOP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Tryndamere.png' },
    { id: 'Urgot', name: '우르곳', role: 'TOP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Urgot.png' },
    { id: 'Volibear', name: '볼리베어', role: 'TOP', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Volibear.png' },
    { id: 'MonkeyKing', name: '오공', role: 'TOP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/MonkeyKing.png' },
    { id: 'Yorick', name: '요릭', role: 'TOP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Yorick.png' },
    { id: 'Ambessa', name: '암베사', role: 'TOP', tier: 2, img: 'champions/Ambessa.webp' },
    { id: 'Zaahen', name: '자헨', role: 'TOP', tier: 1, img: 'champions/Zaahen.webp' },

    // JUG
    { id: 'Amumu', name: '아무무', role: 'JUG', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Amumu.png' },
    { id: 'Belveth', name: '벨베스', role: 'JUG', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Belveth.png' },
    { id: 'Briar', name: '브라이어', role: 'JUG', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Briar.png' },
    { id: 'Diana', name: '다이애나', role: 'JUG', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Diana.png' },
    { id: 'Ekko', name: '에코', role: 'JUG', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ekko.png' },
    { id: 'Elise', name: '엘리스', role: 'JUG', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Elise.png' },
    { id: 'Evelynn', name: '이블린', role: 'JUG', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Evelynn.png' },
    { id: 'Fiddlesticks', name: '피들스틱', role: 'JUG', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Fiddlesticks.png' },
    { id: 'Hecarim', name: '헤카림', role: 'JUG', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Hecarim.png' },
    { id: 'Ivern', name: '아이번', role: 'JUG', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ivern.png' },
    { id: 'JarvanIV', name: '자르반 4세', role: 'JUG', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/JarvanIV.png' },
    { id: 'Karthus', name: '카서스', role: 'JUG', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Karthus.png' },
    { id: 'Kayn', name: '케인', role: 'JUG', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kayn.png' },
    { id: 'Khazix', name: '카직스', role: 'JUG', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Khazix.png' },
    { id: 'Kindred', name: '킨드레드', role: 'JUG', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kindred.png' },
    { id: 'LeeSin', name: '리 신', role: 'JUG', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/LeeSin.png' },
    { id: 'Lillia', name: '릴리아', role: 'JUG', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Lillia.png' },
    { id: 'Maokai', name: '마오카이', role: 'JUG', tier: 'OP', img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Maokai.png' },
    { id: 'MasterYi', name: '마스터 이', role: 'JUG', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/MasterYi.png' },
    { id: 'Nidalee', name: '니달리', role: 'JUG', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Nidalee.png' },
    { id: 'Nocturne', name: '녹턴', role: 'JUG', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Nocturne.png' },
    { id: 'Nunu', name: '누누와 윌럼프', role: 'JUG', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Nunu.png' },
    { id: 'Rammus', name: '람머스', role: 'JUG', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Rammus.png' },
    { id: 'RekSai', name: '렉사이', role: 'JUG', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/RekSai.png' },
    { id: 'Rengar', name: '렝가', role: 'JUG', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Rengar.png' },
    { id: 'Sejuani', name: '세주아니', role: 'JUG', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Sejuani.png' },
    { id: 'Shaco', name: '샤코', role: 'JUG', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Shaco.png' },
    { id: 'Shyvana', name: '쉬바나', role: 'JUG', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Shyvana.png' },
    { id: 'Skarner', name: '스카너', role: 'JUG', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Skarner.png' },
    { id: 'Trundle', name: '트런들', role: 'JUG', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Trundle.png' },
    { id: 'Udyr', name: '우디르', role: 'JUG', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Udyr.png' },
    { id: 'Vi', name: '바이', role: 'JUG', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Vi.png' },
    { id: 'Viego', name: '비에고', role: 'JUG', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Viego.png' },
    { id: 'Warwick', name: '워윅', role: 'JUG', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Warwick.png' },
    { id: 'XinZhao', name: '신 짜오', role: 'JUG', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/XinZhao.png' },
    { id: 'Zac', name: '자크', role: 'JUG', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Zac.png' },
    { id: 'Zaahen', name: '자헨', role: 'JUG', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Zaahen.png' },

    // MID
    { id: 'Ahri', name: '아리', role: 'MID', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ahri.png' },
    { id: 'Akali', name: '아칼리', role: 'MID', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Akali.png' },
    { id: 'Akshan', name: '아크샨', role: 'MID', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Akshan.png' },
    { id: 'Anivia', name: '애니비아', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Anivia.png' },
    { id: 'Annie', name: '애니', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Annie.png' },
    { id: 'AurelionSol', name: '아우렐리온 솔', role: 'MID', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/AurelionSol.png' },
    { id: 'Azir', name: '아지르', role: 'MID', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Azir.png' },
    { id: 'Cassiopeia', name: '카시오페아', role: 'MID', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Cassiopeia.png' },
    { id: 'Corki', name: '코르키', role: 'MID', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Corki.png' },
    { id: 'Fizz', name: '피즈', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Fizz.png' },
    { id: 'Galio', name: '갈리오', role: 'MID', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Galio.png' },
    { id: 'Heimerdinger', name: '하이머딩거', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Heimerdinger.png' },
    { id: 'Hwei', name: '흐웨이', role: 'MID', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Hwei.png' },
    { id: 'Kassadin', name: '카사딘', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kassadin.png' },
    { id: 'Katarina', name: '카타리나', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Katarina.png' },
    { id: 'Leblanc', name: '르블랑', role: 'MID', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Leblanc.png' },
    { id: 'Lissandra', name: '리산드라', role: 'MID', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Lissandra.png' },
    { id: 'Lux', name: '럭스', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Lux.png' },
    { id: 'Malzahar', name: '말자하', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Malzahar.png' },
    { id: 'Naafiri', name: '나파리', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Naafiri.png' },
    { id: 'Neeko', name: '니코', role: 'MID', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Neeko.png' },
    { id: 'Orianna', name: '오리아나', role: 'MID', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Orianna.png' },
    { id: 'Qiyana', name: '키아나', role: 'MID', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Qiyana.png' },
    { id: 'Ryze', name: '라이즈', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ryze.png' },
    { id: 'Swain', name: '스웨인', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Swain.png' },
    { id: 'Sylas', name: '사일러스', role: 'MID', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Sylas.png' },
    { id: 'Syndra', name: '신드라', role: 'MID', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Syndra.png' },
    { id: 'Taliyah', name: '탈리야', role: 'MID', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Taliyah.png' },
    { id: 'Talon', name: '탈론', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Talon.png' },
    { id: 'TwistedFate', name: '트위스티드 페이트', role: 'MID', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/TwistedFate.png' },
    { id: 'Veigar', name: '베이가', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Veigar.png' },
    { id: 'Velkoz', name: '벨코즈', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Velkoz.png' },
    { id: 'Vex', name: '벡스', role: 'MID', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Vex.png' },
    { id: 'Viktor', name: '빅토르', role: 'MID', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Viktor.png' },
    { id: 'Vladimir', name: '블라디미르', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Vladimir.png' },
    { id: 'Xerath', name: '제라스', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Xerath.png' },
    { id: 'Yasuo', name: '야스오', role: 'MID', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Yasuo.png' },
    { id: 'Yone', name: '요네', role: 'MID', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Yone.png' },
    { id: 'Zed', name: '제드', role: 'MID', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Zed.png' },
    { id: 'Ziggs', name: '직스', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ziggs.png' },
    { id: 'Zoe', name: '조이', role: 'MID', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Zoe.png' },
    { id: 'Aurora', name: '오로라', role: 'MID', tier: 2, img: 'champions/Aurora.webp' },
    { id: 'Mel', name: '멜', role: 'MID', tier: 2, img: 'champions/Mel.webp' },

    // BOT
    { id: 'Aphelios', name: '아펠리오스', role: 'BOT', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Aphelios.png' },
    { id: 'Ashe', name: '애쉬', role: 'BOT', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ashe.png' },
    { id: 'Caitlyn', name: '케이틀린', role: 'BOT', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Caitlyn.png' },
    { id: 'Draven', name: '드레이븐', role: 'BOT', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Draven.png' },
    { id: 'Ezreal', name: '이즈리얼', role: 'BOT', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ezreal.png' },
    { id: 'Jhin', name: '진', role: 'BOT', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Jhin.png' },
    { id: 'Jinx', name: '징크스', role: 'BOT', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Jinx.png' },
    { id: 'Kaisa', name: '카이사', role: 'BOT', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kaisa.png' },
    { id: 'Kalista', name: '칼리스타', role: 'BOT', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kalista.png' },
    { id: 'KogMaw', name: '코그모', role: 'BOT', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/KogMaw.png' },
    { id: 'Lucian', name: '루시안', role: 'BOT', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Lucian.png' },
    { id: 'MissFortune', name: '미스 포츈', role: 'BOT', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/MissFortune.png' },
    { id: 'Nilah', name: '닐라', role: 'BOT', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Nilah.png' },
    { id: 'Samira', name: '사미라', role: 'BOT', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Samira.png' },
    { id: 'Sivir', name: '시비르', role: 'BOT', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Sivir.png' },
    { id: 'Smolder', name: '스몰더', role: 'BOT', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Smolder.png' },
    { id: 'Tristana', name: '트리스타나', role: 'BOT', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Tristana.png' },
    { id: 'Twitch', name: '트위치', role: 'BOT', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Twitch.png' },
    { id: 'Varus', name: '바루스', role: 'BOT', tier: 'OP', img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Varus.png' },
    { id: 'Vayne', name: '베인', role: 'BOT', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Vayne.png' },
    { id: 'Xayah', name: '자야', role: 'BOT', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Xayah.png' },
    { id: 'Zeri', name: '제리', role: 'BOT', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Zeri.png' },
    { id: 'Yunara', name: '유나라', role: 'BOT', tier: 1, img: 'champions/Yunara.webp' },

    // SUP
    { id: 'Alistar', name: '알리스타', role: 'SUP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Alistar.png' },
    { id: 'Bard', name: '바드', role: 'SUP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Bard.png' },
    { id: 'Blitzcrank', name: '블리츠크랭크', role: 'SUP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Blitzcrank.png' },
    { id: 'Braum', name: '브라움', role: 'SUP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Braum.png' },
    { id: 'Janna', name: '잔나', role: 'SUP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Janna.png' },
    { id: 'Karma', name: '카르마', role: 'SUP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Karma.png' },
    { id: 'Leona', name: '레오나', role: 'SUP', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Leona.png' },
    { id: 'Lulu', name: '룰루', role: 'SUP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Lulu.png' },
    { id: 'Milio', name: '밀리오', role: 'SUP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Milio.png' },
    { id: 'Morgana', name: '모르가나', role: 'SUP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Morgana.png' },
    { id: 'Nami', name: '나미', role: 'SUP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Nami.png' },
    { id: 'Nautilus', name: '노틸러스', role: 'SUP', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Nautilus.png' },
    { id: 'Pyke', name: '파이크', role: 'SUP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Pyke.png' },
    { id: 'Rakan', name: '라칸', role: 'SUP', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Rakan.png' },
    { id: 'Rell', name: '렐', role: 'SUP', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Rell.png' },
    { id: 'Renata', name: '레나타 글라스크', role: 'SUP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Renata.png' },
    { id: 'Senna', name: '세나', role: 'SUP', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Senna.png' },
    { id: 'Seraphine', name: '세라핀', role: 'SUP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Seraphine.png' },
    { id: 'Sona', name: '소나', role: 'SUP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Sona.png' },
    { id: 'Soraka', name: '소라카', role: 'SUP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Soraka.png' },
    { id: 'TahmKench', name: '탐 켄치', role: 'SUP', tier: 2, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/TahmKench.png' },
    { id: 'Taric', name: '타릭', role: 'SUP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Taric.png' },
    { id: 'Thresh', name: '쓰레쉬', role: 'SUP', tier: 1, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Thresh.png' },
    { id: 'Yuumi', name: '유미', role: 'SUP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Yuumi.png' },
    { id: 'Zilean', name: '질리언', role: 'SUP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Zilean.png' },
    { id: 'Zyra', name: '자이라', role: 'SUP', tier: 3, img: 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Zyra.png' }
  ]
};
